#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

picom -b &

hsetroot -solid "#000000" &
xsetroot -cursor_name left_ptr &
setxkbmap us intl &

xrandr | grep "HDMI-1 connected" && xrandr --output HDMI-1 --mode 3440x1440 --rate 49.95 --primary && xrandr --output eDP-1 --off && xrandr --output eDP-2 --off &

# Start Polybar
$HOME/.config/polybar/launch.sh &

# Start NetworkManager applet
nm-applet &

# Lock screen before suspend
xss-lock --transfer-sleep-lock -- i3lock -c 000000 --nofork &

# Border settings
bspc config border_width 1
bspc config normal_border_color "#000000"

# Gaps and Monocle behavior
bspc config window_gap 10
bspc config borderless_monocle true
bspc config gapless_monocle true

# Window focus behavior
bspc config focus_follows_pointer true

# Window splitting
bspc config split_ratio 0.5

# Move window
bspc config pointer_modifier mod1
