hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("waybar")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("nm-applet")
    -- hl.exec_cmd("hyprpaper")
    hl.exec_cmd("openrgb --device 0 --mode Custom --color c080ff")
end)
