# ~/.config/kitty/kitty.conf

# Theme
include ~/.config/kitty/catppuccin-mocha.conf

# Font
font_family      family="ComicShannsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        13.0

# Background
background #000000

# Disable kitty tab bar
tab_bar_style hidden

# No startup session behavior
shell_integration no-cursor

# Disable most kitty extras
enable_audio_bell no
confirm_os_window_close 0
remember_window_size no

# Make terminal feel more "raw"
strip_trailing_spaces never

# Remove window padding
window_padding_width 0

# Optional: no ligatures
disable_ligatures never

# Keep tmux colors correct
term xterm-kitty

# Mouse
copy_on_select yes
